#!/bin/bash
#------------------------------
# This script makes a backup of various configuration files, by moljac024
#------------------------------
# Configuration:
backupDir="$HOME/Backup"
#------------------------------

# set -o nounset

if [[ $EUID = 0 ]]; then
    echo "Ooops, you're running this as root! You better not!"
    exit 1
fi

backupConfigs () {
    echo "Backing up configs.."
    cd "$HOME"
    tar -czf "$backupDir"/Configs.tar.gz \
        .bashrc .bash.mine \
        .tmux.conf .mpdconf \
        .rtorrent.rc .dosbox/ \
        .conkyrc .ssh/ .i3/ \
        .weechat/ .wine/ .wine-bottles/ \
        .Xresources .xmodmap .xmonad/ \
        .config/conky/ .config/Terminal/ \
        .config/awesome/ .config/openbox/ \
        &> /dev/null
}

backupScripts () {
    echo "Backing up scripts.."
    cd $HOME
    tar -czf "$backupDir"/Scripts.tar.gz \
        bin/ \
        &> /dev/null
}

backupNotes () {
    echo "Backing up notes.."
    cd $HOME
    tar -czf "$backupDir"/Notes.tar.gz \
        .emacs.d/org/ \
        .vim/notes/ \
        &> /dev/null
}

backupTemplates () {
    echo "Backing up template files.."
    cd $HOME
    tar -czf "$backupDir"/Templates.tar.gz \
        Templates/ \
        &> /dev/null
}

backupThemes () {
    echo "Backing up themes.."
    cd $HOME
    tar -czf "$backupDir"/Themes.tar.gz \
        .icons/ .themes/ \
        &> /dev/null
}

backupFonts () {
    echo "Backing up fonts.."
    cd $HOME
    tar -czf "$backupDir"/Fonts.tar.gz \
        .fonts/ \
        &> /dev/null
}

backupVim () {
    echo "Backing up vim.."
    cd $HOME
    tar -czf "$backupDir"/Vim.tar.gz \
        .vimrc .vim/ \
        &> /dev/null
}

backupEmacs () {
    echo "Backing up emacs.."
    cd $HOME
    tar -czf "$backupDir"/Emacs.tar.gz \
        .emacs.d/ \
        &> /dev/null
}

backupProjects () {
    echo "Backing up project files.."
    cd "$HOME"
    tar -czf "$backupDir"/Projects.tar.gz \
        Projects/ \
        &> /dev/null
}

backupConfigs
backupScripts
backupNotes
backupTemplates
backupThemes
backupFonts
if [[ "$1" != "--min" ]]; then
    backupVim
    backupEmacs
    backupProjects
fi
exit 0
