#!/bin/bash

#Customize this stuff
IF="Master"
SECS="0.4"

FONT="-*-terminus-medium-r-normal-*-14-*-*-*-*-*-*-*"
BG="black"
FG="white"
XPOS="0"
YPOS="0"
WIDTH="1280"

#Probably do not customize
PIPE="/tmp/dvolpipe"

err() {
    echo "$1"
    exit 1
}

usage() {
    echo "usage: dvol [option] [argument]"
    echo
    echo "Options:"
    echo "     -i, --increase - increase volume by \`argument'"
    echo "     -d, --decrease - decrease volume by \`argument'"
    echo "     -t, --toggle   - toggle mute on and off"
    echo "     -h, --help     - display this"
    exit
}

#Argument Parsing
case "$1" in
    '-i'|'--increase')
        [ -z "$2" ] && err "No argument specified for increase."
        AMIXARG="${2}%+"
        ;;
    '-d'|'--decrease')
        [ -z "$2" ] && err "No argument specified for decrease."
        AMIXARG="${2}%-"
        ;;
    '-t'|'--toggle')
        AMIXARG="toggle"
        ;;
    ''|'-h'|'--help')
        usage
        ;;
    *)
        err "Unrecognized option \`$1', see dvol --help"
        ;;
esac

#Actual volume changing (readability low)
AMIXOUT="$(amixer set "$IF" "$AMIXARG" | tail -n 1)"
MUTE="$(cut -d '[' -f 4 <<<"$AMIXOUT")"
if [ "$MUTE" = "off]" ]; then
    VOL="0"
else
    VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
fi

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -e "$PIPE" ]; then
    mkfifo "$PIPE"
    (dzen2 -l 1 -x "$XPOS" -y "$YPOS" -w "$WIDTH" -fn "$FONT" -bg "$BG" -fg "$FG" -e '' < "$PIPE"
    rm -f "$PIPE") &
fi

#Feed the pipe!
(echo -n "^fg(orange)Volume: ^fg()" ; echo "$VOL" | dbar ; sleep "$SECS") > "$PIPE"
