#!/bin/bash
#-----------------------
# A dzen notification script, by moljac024
#-----------------------
# Configuration:
#-----------------------
#DZEN_FONT="-*-terminus-*-*-*-*-14-*-*-*-*-*-*-*"
DZEN_FONT="-*-*-bold-r-*-*-20-*-*-*-*-*-*-*"
DZEN_BG="#494949"
DZEN_FG="#ffffff"
DZEN_WIDTH=400
DZEN_HEIGHT=32
DZEN_DURATION=5
DZEN_X_POS=0
DZEN_Y_POS=0
#-----------------------

MESSAGE="Testing, testing...you forgot to pass a message didn't you?"

if [[ "$#" == "1" ]]; then
    MESSAGE="$1"
elif [[ "$#" > "1" ]]; then
    MESSAGE="$1"
    DZEN_DURATION="$2"
fi

echo "$MESSAGE" | dzen2 -p "$DZEN_DURATION" -bg "$DZEN_BG" -fg "$DZEN_FG" -fn "$DZEN_FONT" -x "$DZEN_X_POS" -y "$DZEN_Y_POS" -w "$DZEN_WIDTH" -h "$DZEN_HEIGHT" -e 'entertitle=grabmouse;leavetitle=ungrabmouse;button1=exit;button2=exit;button3=exit'
