#!/bin/bash
#------------------------------
# Set wallpaper with feh
#------------------------------
# Configuration:
#------------------------------
WALLPAPER_DIR=$HOME/Pictures/Wallpapers
#------------------------------

feh --bg-fill "$@"
