#!/bin/bash
# Set the sensitivity for the supplied mouse

mouse_name=$1
mouse_sensitivity=3
if [[ $# > 1 ]]; then
    mouse_sensitivity=$2
fi

function get_mouse_id() {
    xinput --list |
    grep "$mouse_name" |
    awk '{print $(NF-3)}' |
    cut -c 4-
}

mouse_id=$(get_mouse_id)

xinput --set-prop $mouse_id 267 $mouse_sensitivity
