#!/bin/bash
# Set the sensitivity for the supplied mouse

if [[ $# < 1 ]]; then
    echo "Please provide device name."
    exit 1
else
    mouse_name=$1
fi

if [[ $# > 1 ]]; then
    mouse_sensitivity=$2
else
    mouse_sensitivity=3
fi

function get_mouse_id() {
    xinput --list |
    grep "$mouse_name" |
    awk '{print $(NF-3)}' |
    cut -c 4-
}

function is_number() {
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; then
        echo 'False'
    else
        echo 'True'
    fi
}

function get_decel_prop() {
    xinput --list-props $1 |
    grep "Device Accel Constant Deceleration" |
    cut -c 38-40
}

mouse_id=$(get_mouse_id)
is_number=$(is_number $mouse_id)

if [[ $is_number == 'True' ]]; then
    prop=$(get_decel_prop $mouse_id)
    xinput --set-prop $mouse_id $prop $mouse_sensitivity
else
    echo 'Device not found!'
    exit 1
fi

