#!/bin/bash

# Check if curl is installed
which curl &> /dev/null
if [[ "$?" != "0" ]]; then
    echo "error: curl not found"
    exit 1
fi

# Check if php is installed
which php &> /dev/null
if [[ "$?" != "0" ]]; then
    echo "error: php not found"
    exit 1
fi

# If composer not present, download it, otherwise update
if [[ ! -f ./composer.phar ]]; then
    curl -s https://getcomposer.org/installer | php
else
    php ./composer.phar self-update
fi

# Clean up those .git directories
if [[ "$@" == "cleanup" ]]; then
    while [[ ! (-d ./vendor) ]]; do
        cd ..
        if [[ $PWD == "/" ]]; then
            echo "error: no vendor directory found"
            exit
        fi
    done
    # find ./vendor -name ".git" -exec rm -rf {} \;
    rm -rf `find ./vendor -type d -name .git`
fi

if [[ "$@" != "self-update" ]]; then
    php ./composer.phar $@
fi
