#!/bin/bash
#------------------------------
# Restore wallpaper
#------------------------------

if xrandr -q | grep "VGA1 disconnected" >/dev/null; then
    . ~/.fehbg
elif xrandr -q | grep "VGA1 connected" >/dev/null; then
    nitrogen --restore
fi
