#!/bin/bash
#------------------------------
# A script for connecting to a wireless connection which utilizes pppoe, by moljac024
#------------------------------
# Configuration:
retryTimes=5
#------------------------------

set -o nounset

sudo ifconfig wlan0 down
sudo ifconfig wlan0 up
sudo pppoe-stop &> /dev/null

retryNumber=0
while [[ $retryNumber -lt $retryTimes ]]
do
    let retryNumber=$retryNumber+1
    echo "Try $retryNumber of $retryTimes:"
    if [[ "$#" -ge "2" ]]
    then
        sudo iwconfig wlan0 mode managed ap auto essid -- "$1" && sudo pppoe-start "$2" \
            && break || sleep 2; continue
    else
        sudo iwconfig wlan0 mode managed ap auto essid -- "$1" && sudo pppoe-start \
            && break || sleep 2; continue
        #sudo iwconfig wlan0 mode managed ap auto essid -- "$1" && sudo pppoe-start
    fi
done
