#!/bin/bash
#------------------------------
# A script for opening a file manager the smart way
#------------------------------
# Configuration:
#------------------------------

# Commands
thunar="thunar"
nautilus="nautilus --no-desktop"

# Default
default_fm=$thunar
#-------------------------------

$default_fm
