#!/bin/bash
#------------------------------
# A script for opening a file manager the smart way
#------------------------------
# Configuration:
#------------------------------
thunar_command="thunar"
nautilus_command="nautilus --no-desktop"

default_fm=$nautilus_command
#-------------------------------

$default_fm
