#!/bin/bash
#------------------------------
# Common applications starter
#------------------------------

# Start emacs server
#emacs-start-server

# SELinux applet
#[ `pgrep seapplet` ] || seapplet &

# Sound mixer
#[ `pgrep pnmixer` ] || pnmixer &

pa="$HOME/.local/bin/pa-applet"
if [[ -f $pa ]]; then
    [ `pgrep pa-applet` ] || $pa &
fi

# Power manager
[ `pgrep xfce4-power-manager` ] || xfce4-power-manager &

# Command launcher
[ `pgrep synapse` ] || synapse -s &

# Command launcher
#[ `pgrep kupfer` ] || kupfer &

# Music daemon
[ `pgrep mpd` ] || mpd &

# Network manager
[ `pgrep nm-applet ` ] || nm-applet &

# Torrent client
#[ `pgrep transmission` ] || transmission-gtk -m &

# Music player
[ `pgrep sonata` ] || sonata --hidden &

# Chat client
[ `pgrep pidgin` ] || pidgin &
