#!/bin/bash
#------------------------------
# X mouse setup
#------------------------------

# Sane mouse acceleration
xset m 1 4

# Check for synclient
command -v synclient >/dev/null 2>&1 || exit 1

# Set up touchpad for tapping
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient VertEdgeScroll=1
