#!/bin/bash
#------------------------------
# X system bootstrapper
#------------------------------

#------------------------------
# Set up monitors
#------------------------------

system-setup-monitors

#------------------------------
# Setup Xorg
#------------------------------

system-setup-xorg

#------------------------------
# Restore wallpaper
#------------------------------

restore-wallpaper

#------------------------------
# Autostart applications
#------------------------------

# Please ubuntu, let me keep my sanity
#eval $(gnome-keyring-daemon --start)

system-setup-autostart
