#!/bin/bash
#------------------------------
# Xorg setup
#------------------------------

#------------------------------
# Xrandr setup
#------------------------------

# Internal laptop monitor
xrandr --output LVDS1 --auto

# External monitor
xrandr --output HDMI1 --auto --left-of LVDS1

#------------------------------
# Xorg server setup
#------------------------------

# Run xrdb if necessary
if [ -f ~/.Xdefaults ]; then
    xrdb ~/.Xdefaults
fi

if [ -f ~/.Xresources ]; then
    xrdb ~/.Xresources
fi

# DPMS timeout
#xset dpms 300 600 900

#------------------------------
# Xorg keyboard setup
#------------------------------

# Run xmodmap if neccesarry
# if [ -f ~/.xmodmap ]; then
#     xmodmap ~/.xmodmap
# fi

# Repeat delay and rate
xset r rate 500 20

# Make caps lock additional control
setxkbmap -option "ctrl:nocaps"

# Set up keyboard layout switching
setxkbmap -layout us,rs,rs -variant ,latinyz,
setxkbmap -option "grp:alt_shift_toggle"

# Turn on numlock
command -v numlockx >/dev/null 2>&1 && numlockx &

#------------------------------
# Xorg mouse setup
#------------------------------

# Sane mouse acceleration
xset m 1 4

# Set up touchpad for tapping
if command -v synclient >/dev/null 2>&1; then
    synclient TapButton1=1
    synclient TapButton2=3
    synclient TapButton3=2
    synclient VertEdgeScroll=1
fi

# Disable tapping initially
synclient TouchpadOff=2
