#!/bin/bash

#ctags -f tags \
    #-h \".php\" -R \
    #--exclude=\"\.svn\" \
    #--totals=yes \
    #--tag-relative=yes \
    #--PHP-kinds=+cf \
    #--regex-PHP='/abstract class ([^ ]*)/\1/c/' \
    #--regex-PHP='/interface ([^ ]*)/\1/c/' \
    #--regex-PHP='/(public |static |abstract |protected |private )+function ([^ (]*)/\2/f/'

ctags -f tags \
    -h ".php" -R \
    --PHP-kinds=cfiv \
    --totals=yes \
    --tag-relative=yes \
    --PHP-kinds=cfiv \
    --regex-PHP='/(abstract)?\s+class\s+([^ ]+)/\2/c/' \
    --regex-PHP='/interface\s+([^ ]+)/\1/i/' \
    --exclude="*.js" \
    --exclude=".svn" \
    --exclude=".git"
