#!/bin/bash

# Get current state of touchpad
STATE=$(synclient -l | grep TouchpadOff | sed -e "s/^.*\(.\)$/\1/")

if [[ $STATE == 0 ]]; then
    synclient TouchpadOff=1
    dzen-msg "Touchpad Off"
elif [[ $STATE == 1 ]]; then
    synclient TouchpadOff=0
    dzen-msg "Touchpad On"
fi

exit 0
