#!/bin/bash

# Get current state of touchpad
STATE=$(synclient -l | grep TouchpadOff | sed -e "s/^.*\(.\)$/\1/")

if [[ $STATE == 0 ]]; then
    synclient TouchpadOff=2
    dzen-msg "Touchpad on (no tapping)"
elif [[ $STATE == 1 ]]; then
    synclient TouchpadOff=0
    dzen-msg "Touchpad On"
elif [[ $STATE == 2 ]]; then
    synclient TouchpadOff=1
    dzen-msg "Touchpad off"
else
    dzen-msg "error, unknown STATE: $STATE"
fi

exit 0
