#!/bin/sh

# Bootstrap environment
system-setup-xorg

# Restore wallpaper
nitrogen --restore

# Thunar daemon
#thunar --daemon &

# Start panel (for the tray)
xfce4-panel &

# Autostart applications
(sleep 2 && system-setup-autostart) &

# Start window manager
exec ~/.cabal/bin/xmonad
