#!/bin/sh

# Bootstrap environment
system-setup-xorg

# Restore wallpaper
nitrogen --restore

# Start panel (for the tray)
xfce4-panel &

# Autostart applications
system-setup-autostart

# Start window manager
exec ~/.cabal/bin/xmonad
